[package]
name = "shi"
version = "0.1.0"
authors = ["may h <mehrabhoque@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
rustyline = "7.1.0"
rustyline-derive = "0.4.0"
colored = "2.0.0"
