name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (all)
      run: cargo build --all-targets --verbose
    - name: Touch all rust files so clippy can report all errors (rust-clippy#4612)
      run: find . | grep "\.rs\$" | xargs touch
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
